### PR TITLE
Make mysql storage backend a configurable option rather than the default

### PR DESCRIPTION
**Pull request by wa5i**
To prevent compilation failures for users who do not require mysql.

### CODE REVIEW

**Comment by wa5i** [comment]
CC @WorldWay

**Comment by InfoHunter** [comment]
Why it will fail if mysql support is compiled by default?

**Comment by wa5i** [comment]
> Why it will fail if mysql support is compiled by default?

Because it depends on the MySQL library, compilation will fail if it is absent.

**Comment by wa5i** [comment]
ping @InfoHunter  @WorldWay

**Review by InfoHunter — APPROVED** [review]

**Pull request merged**
