### PR TITLE
fix some obvious typos

### PR DESCRIPTION
**Pull request by varshard**
Fix some obvious typos.

Spotted some typos while reading documents. So, I decided to correct them while I'm at it.

### CODE REVIEW

**Comment by varshard** [comment]
Suggestiong, it would be nice if we use `1.` for evevery numbered item as GitHub and most of the markdown renderers are smart enough to change them properly.

```
1. this is first
1. this is second
```

**Review by wa5i — APPROVED** [review]
LGTM, thank you for the feedback!

**Comment by InfoHunter** [comment]
Seems I should use VIM to check typos before commit the files. Thanks for the fixes

**Comment by InfoHunter** [comment]
> Suggestiong, it would be nice if we use 1. for evevery numbered item as GitHub and most of the markdown renderers are smart enough to change them properly.

Yes, I will address that later in another pull request.

**Comment by InfoHunter** [comment]
Hi @varshard , we add a CLA file to RustyVault, so would you please sign that file online to make sure you agree with the statements?

**Comment by InfoHunter** [comment]
It seems you can utilize this link: https://cla-assistant.io/Tongsuo-Project/RustyVault

**Pull request merged**
